version: "3"
services:
  nginx:
    container_name: lara-nginx
    image: nginx
    working_dir: /www
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/www:delegated
      - ./storage:/www/storage:delegated
    command: /bin/sh -c "chown -R www-data:www-data /www/storage && nginx -g 'daemon off;'"
  php:
    container_name: lara-php
    image: lostdesign/laravel:1.2
    working_dir: /www
    volumes:
      - ./:/www:delegated
      - ./storage:/www/storage:delegated
    command: /bin/sh -c "chmod -R 777 /www/storage && php-fpm"
  mysql:
    container_name: lara-mysql
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
  redis:
    container_name: lara-redis
    image: redis
    ports:
      - "6382:6379"
  metabase:
    container_name: lara-metabase
    image: metabase/metabase
    ports:
      - "3000:3000"